### ISSUE TITLE
Fix unclosed files

### ISSUE THREAD

**Issue by Tch1b0** [Wes1101/adventOfCode2022#1]
## Problem

The files in myFileModule.py line [7](https://github.com/Wes1101/adventOfCode2022/blob/30e46158eb00685e60d0c6947fb28cc2a23d93a4/_helper/modules/myFileModule.py#L7) and [23](https://github.com/Wes1101/adventOfCode2022/blob/30e46158eb00685e60d0c6947fb28cc2a23d93a4/_helper/modules/myFileModule.py#L23) both are never closed. This causes them to stay in memory for longer than they need to.

## Solution

You could close the file in the verbose way: `<file>.close()` or furthermore you could use a neat feature of python that includes the `with` keyword:
```py
with open("path/to/file.txt", "r") as file:
    # in this scope, the variable "file" is available
    file.write("Hello, World!")

# no file.close() needed, The file closes itself!
# also, the variable "file" stops existing here, as it is out of scope
```

Read more about python's `with` statement: [stackoverflow](https://stackoverflow.com/questions/1369526/what-is-the-python-keyword-with-used-for), [geeksforgeeks](https://www.geeksforgeeks.org/with-statement-in-python/), [realpython](https://realpython.com/python-with-statement/)

**Comment by Wes1101** [comment]
Better now?

**Comment by Tch1b0** [comment]
Looks great
